import { UiMainContainer } from "@/components/uikit/ui-main-container";
import { PaymentHead } from "@/components/payment";

export const metadata = {
    title: "NIKO | Оплата подписки",
    description: "Generated by create next app",
};

export default function PaymentPage() {
    return (
        <UiMainContainer>
            <PaymentHead />
        </UiMainContainer>
    );
}
