import { UiMainContainer } from "@/components/uikit/ui-main-container";
import {
    AccountHead,
    AccountInfo,
    AccountSubscribe,
} from "@/components/account";

export const metadata = {
    title: "NIKO | Личный кабинет",
    description: "Generated by create next app",
};

export default function AccountAppPage() {
    return (
        <UiMainContainer>
            <AccountHead />
            <AccountInfo />
            <AccountSubscribe />
        </UiMainContainer>
    );
}
