import { Roboto } from "next/font/google";
import "./globals.css";

import { Navigate } from "@/components/navigate";

const roboto = Roboto({
    weight: ["400", "700"],
    subsets: ["cyrillic", "latin"],
    display: "swap",
});

export const metadata = {
    title: "NIKO",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="ru">
            <body className={roboto.className}>
                <Navigate />

                {children}
            </body>
        </html>
    );
}
