import { AboutHead, AboutModes } from "@/components/about";
import { UiMainContainer } from "@/components/uikit/ui-main-container";

export const metadata = {
    title: "NIKO | О приложении",
    description: "Generated by create next app",
};

export default function AboutAppPage() {
    return (
        <UiMainContainer>
            <AboutHead />
            <AboutModes />
        </UiMainContainer>
    );
}
