import { UiMainContainer } from "@/components/uikit/ui-main-container";
import { AboutHead, AboutModes, AboutSubscribe } from "@/components/about";

export const metadata = {
    title: "NIKO | О приложении",
    description: "Generated by create next app",
};

export default function AboutAppPage() {
    return (
        <UiMainContainer>
            <AboutHead />
            <AboutModes />
            <AboutSubscribe />
        </UiMainContainer>
    );
}
