import { UiMainContainer } from "@/components/uikit/ui-main-container";
import {
    AccountHead,
    AccountInfo,
    AccountSubscribe,
} from "@/components/account";
import { currentUser } from "@/lib/auth";

export const metadata = {
    title: "NIKO | Личный кабинет",
    description: "Generated by create next app",
};

export default async function AccountAppPage() {
    const user = await currentUser();

    return (
        <UiMainContainer>
            <AccountHead />
            <AccountInfo user={user} />
            <AccountSubscribe />
        </UiMainContainer>
    );
}
